/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Agent
         * @description Register a new Agent from its manifest. Returns AgentProfile.
         */
        post: operations["create_agent_agents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/{agent_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Agent
         * @description Get AgentProfile by ID.
         */
        get: operations["get_agent_agents__agent_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/{agent_id}/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Agent Graph
         * @description Get AttackGraph for an agent.
         */
        get: operations["get_agent_graph_agents__agent_id__graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evaluations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Evaluation */
        post: operations["create_evaluation_evaluations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evaluations/{evaluation_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Evaluation */
        post: operations["start_evaluation_evaluations__evaluation_id__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evaluations/{evaluation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Evaluation */
        get: operations["get_evaluation_evaluations__evaluation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evaluations/{evaluation_id}/trace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Evaluation Trace */
        get: operations["get_evaluation_trace_evaluations__evaluation_id__trace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evaluations/{evaluation_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Evaluation Report */
        get: operations["get_evaluation_report_evaluations__evaluation_id__report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evaluations/{evaluation_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Evaluation Events */
        get: operations["stream_evaluation_events_evaluations__evaluation_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AgentManifest
         * @description 用户接入 Agent 时提交的声明文件.
         */
        AgentManifest: {
            /**
             * Agent Id
             * @description Agent 唯一标识
             */
            agent_id: string;
            /**
             * Name
             * @description Agent 名称
             */
            name: string;
            /**
             * Version
             * @description 版本号
             * @default 0.1.0
             */
            version: string;
            /**
             * Capabilities
             * @description 能力清单(工具名)
             */
            capabilities?: string[];
            /**
             * Data Sources
             * @description 数据源列表
             */
            data_sources?: string[];
            /**
             * Memory
             * @description 记忆配置
             */
            memory?: {
                [key: string]: unknown;
            };
            /**
             * Tool Permissions
             * @description 工具权限映射, tool_name → ALLOW|CONFIRM|DENY
             */
            tool_permissions?: {
                [key: string]: string;
            };
        };
        /** ApiErrorDetail */
        ApiErrorDetail: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Details */
            details: {
                [key: string]: unknown;
            };
        };
        /** ApiErrorResponse */
        ApiErrorResponse: {
            error: components["schemas"]["ApiErrorDetail"];
        };
        /** CreateEvaluationRequest */
        CreateEvaluationRequest: {
            /** Request Id */
            request_id: string;
            /** Agent Id */
            agent_id: string;
            /** Test Case Ids */
            test_case_ids: string[];
        };
        /** EvaluationError */
        EvaluationError: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Retryable */
            retryable: boolean;
        };
        /**
         * EvaluationReport
         * @description 安全测评上线报告.
         */
        EvaluationReport: {
            /**
             * Report Id
             * @description 报告唯一标识
             */
            report_id: string;
            /**
             * Evaluation Id
             * @description 关联的 Evaluation ID
             */
            evaluation_id: string;
            /**
             * Agent Id
             * @description 被测 Agent ID
             */
            agent_id: string;
            /**
             * Overall Score
             * @description 综合评分
             * @default 0
             */
            overall_score: number;
            /**
             * Severity
             * @description 最高严重等级
             * @default LOW
             */
            severity: string;
            /**
             * Findings
             * @description 风险发现列表
             */
            findings?: components["schemas"]["RiskFinding"][];
            /**
             * Conclusion
             * @description 测评结论
             * @default
             */
            conclusion: string;
            score_breakdown: components["schemas"]["ScoreBreakdown"];
            /**
             * Summary
             * @description L6: 批量统计摘要 (可选)
             */
            summary?: components["schemas"]["ReportSummary"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
        };
        /**
         * EvaluationRun
         * @description 一次安全测评的运行实例.
         */
        EvaluationRun: {
            /**
             * Run Id
             * @description Run 唯一标识
             */
            run_id: string;
            /**
             * Agent Id
             * @description 被测 Agent ID
             */
            agent_id: string;
            /**
             * Test Case Ids
             * @description 执行的 TestCase ID 列表
             */
            test_case_ids: string[];
            /**
             * Status
             * @description 运行状态
             * @enum {string}
             */
            status: "preflighting" | "ready" | "preflight_failed" | "queued" | "running" | "completed" | "failed" | "interrupted";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Current Stage */
            current_stage?: ("web_content_injection" | "persistent_memory_poisoning" | "unconfirmed_email_send") | null;
            /**
             * Last Event Seq
             * @default 0
             */
            last_event_seq: number;
            /**
             * Report Available
             * @default false
             */
            report_available: boolean;
            error?: components["schemas"]["EvaluationError"] | null;
        };
        /**
         * EventType
         * @description 事件类型 — §2.1 冻结.
         * @enum {string}
         */
        EventType: "RUN_STARTED" | "ANATOMY_READY" | "RISK_PATH_FOUND" | "TEST_STARTED" | "SEED_SELECTED" | "MUTATION_CREATED" | "TOOL_CALLED" | "MEMORY_WRITTEN" | "JUDGE_DECISION" | "FINDING_CREATED" | "RUN_FINISHED" | "PREFLIGHT_COMPLETED" | "PREFLIGHT_FAILED" | "AGENT_INVOKED" | "AGENT_RESPONDED" | "TOOL_RESULT" | "RUN_FAILED" | "TEST_COMPLETED";
        /**
         * ExecutionEvent
         * @description 运行时统一事件, 用于 Trace 和 SSE.
         */
        ExecutionEvent: {
            /**
             * Event Id
             * @description 事件唯一标识
             */
            event_id: string;
            /**
             * Run Id
             * @description 所属 Run ID
             */
            run_id: string;
            /**
             * Timestamp
             * Format: date-time
             * @description 事件时间戳
             */
            timestamp: string;
            /** @description 事件类型, 见 EventType 枚举 */
            type: components["schemas"]["EventType"];
            /**
             * Payload
             * @description 事件负载
             */
            payload?: {
                [key: string]: unknown;
            };
        };
        /**
         * ExecutionTrace
         * @description 一次 Agent 执行的完整事件轨迹.
         */
        ExecutionTrace: {
            /**
             * Trace Id
             * @description Trace 唯一标识
             */
            trace_id: string;
            /**
             * Run Id
             * @description 所属 Run ID
             */
            run_id: string;
            /**
             * Agent Id
             * @description Agent ID
             */
            agent_id: string;
            /**
             * Events
             * @description 事件序列
             */
            events?: components["schemas"]["ExecutionEvent"][];
        };
        /**
         * FindingEvidence
         * @description RiskFinding 中的证据条目.
         */
        FindingEvidence: {
            /**
             * Event Id
             * @description 证据事件 ID
             */
            event_id: string;
            /**
             * Description
             * @description 证据描述
             */
            description: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ReportSummary
         * @description L6: 批量执行统计摘要.
         */
        ReportSummary: {
            /** @default 0 */
            total_tests?: number;
            /** @default 0 */
            passed?: number;
            /** @default 0 */
            failed?: number;
            /** @default 0 */
            error?: number;
            /**
             * @default 0
             * @description 通过率 (0.0-1.0)
             */
            pass_rate?: number;
            /** @description 按 RiskPattern 维度统计 (R1/R2/R3/R4 → {total, passed, failed, error}) */
            by_risk_pattern?: Record<string, Record<string, number>>;
            /** @description 按 risk_type 维度统计 */
            by_risk_type?: Record<string, Record<string, number>>;
            /** @description 按 severity 维度统计 */
            by_severity?: Record<string, Record<string, number>>;
        };
        /**
         * RiskFinding
         * @description 一条确认的风险发现.
         */
        RiskFinding: {
            /**
             * Finding Id
             * @description Finding 唯一标识
             */
            finding_id: string;
            /**
             * Evaluation Id
             * @description 所属 Evaluation ID
             */
            evaluation_id: string;
            /**
             * Risk Type
             * @description 风险类型枚举值
             */
            risk_type: string;
            /**
             * Severity
             * @description 严重等级
             */
            severity: string;
            /**
             * Risk Pattern Id
             * @description 关联的 RiskPattern ID
             */
            risk_pattern_id: string;
            /**
             * Attack Path Id
             * @description 关联的 AttackPath ID
             */
            attack_path_id?: string | null;
            /**
             * Description
             * @description 风险描述
             */
            description: string;
            /**
             * Evidence
             * @description 证据列表
             */
            evidence?: components["schemas"]["FindingEvidence"][];
            /**
             * Rule Types
             * @description 命中的规则类型
             */
            rule_types?: string[];
            /**
             * Remediation
             * @description 处置建议
             */
            remediation?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
        };
        /** ScoreBreakdown */
        ScoreBreakdown: {
            /**
             * Algorithm Version
             * @default r4-mvp-v1
             * @constant
             */
            algorithm_version: "r4-mvp-v1";
            dimensions: components["schemas"]["ScoreDimensions"];
            weights?: components["schemas"]["ScoreWeights"];
            /** Deductions */
            deductions?: components["schemas"]["ScoreDeduction"][];
            severity_cap?: components["schemas"]["SeverityCap"] | null;
        };
        /** ScoreDeduction */
        ScoreDeduction: {
            /**
             * Dimension
             * @enum {string}
             */
            dimension: "capability" | "execution_stability" | "security";
            /** Rule Type */
            rule_type: string;
            /** Points */
            points: number;
            /** Evidence Event Ids */
            evidence_event_ids?: string[];
        };
        /** ScoreDimensions */
        ScoreDimensions: {
            /** Capability */
            capability: number;
            /** Execution Stability */
            execution_stability: number;
            /** Security */
            security: number;
        };
        /** ScoreWeights */
        ScoreWeights: {
            /**
             * Capability
             * @default 25
             * @constant
             */
            capability: 25;
            /**
             * Execution Stability
             * @default 20
             * @constant
             */
            execution_stability: 20;
            /**
             * Security
             * @default 55
             * @constant
             */
            security: 55;
        };
        /** SeverityCap */
        SeverityCap: {
            /**
             * Severity
             * @enum {string}
             */
            severity: "HIGH" | "CRITICAL";
            /**
             * Maximum Score
             * @enum {integer}
             */
            maximum_score: 39 | 59;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    create_agent_agents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentManifest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_agent_agents__agent_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_agent_graph_agents__agent_id__graph_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_evaluation_evaluations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEvaluationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationRun"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    start_evaluation_evaluations__evaluation_id__start_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evaluation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationRun"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evaluation_evaluations__evaluation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evaluation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationRun"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evaluation_trace_evaluations__evaluation_id__trace_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evaluation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecutionTrace"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evaluation_report_evaluations__evaluation_id__report_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evaluation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_evaluation_events_evaluations__evaluation_id__events_get: {
        parameters: {
            query?: {
                after?: number;
            };
            header?: {
                "Last-Event-ID"?: string | null;
            };
            path: {
                evaluation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
