/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Agent
         * @description Register a new Agent from its manifest. Returns AgentProfile.
         */
        post: operations["create_agent_agents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/{agent_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Agent
         * @description Get AgentProfile by ID.
         */
        get: operations["get_agent_agents__agent_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/{agent_id}/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Agent Graph
         * @description Get AttackGraph for an agent.
         */
        get: operations["get_agent_graph_agents__agent_id__graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evaluations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Evaluation */
        post: operations["create_evaluation_evaluations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evaluations/{evaluation_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Evaluation */
        post: operations["start_evaluation_evaluations__evaluation_id__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evaluations/{evaluation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Evaluation */
        get: operations["get_evaluation_evaluations__evaluation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evaluations/{evaluation_id}/trace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Evaluation Trace */
        get: operations["get_evaluation_trace_evaluations__evaluation_id__trace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evaluations/{evaluation_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Evaluation Report */
        get: operations["get_evaluation_report_evaluations__evaluation_id__report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evaluations/{evaluation_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Evaluation Events */
        get: operations["stream_evaluation_events_evaluations__evaluation_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/test-cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Test Cases
         * @description 返回全部 TestCase 摘要 (供前端选择器 + OpenAPI types 生成).
         */
        get: operations["list_test_cases_test_cases_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/test-cases/{test_case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Test Case
         * @description 返回单个完整 TestCase (含 scenario.turns + env_delta), 供前端/联调消费.
         *
         *     L4 签字备注: Frontend 以 OpenAPI schema 为准, 消费 ScenarioTurn.input /
         *     ScenarioTurn.env_delta / turn_count 等字段。
         */
        get: operations["get_test_case_test_cases__test_case_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AgentManifest
         * @description 用户接入 Agent 时提交的声明文件.
         */
        AgentManifest: {
            /**
             * Agent Id
             * @description Agent 唯一标识
             */
            agent_id: string;
            /**
             * Name
             * @description Agent 名称
             */
            name: string;
            /**
             * Version
             * @description 版本号
             * @default 0.1.0
             */
            version: string;
            /**
             * Capabilities
             * @description 能力清单(工具名)
             */
            capabilities?: string[];
            /**
             * Data Sources
             * @description 数据源列表
             */
            data_sources?: string[];
            /**
             * Memory
             * @description 记忆配置
             */
            memory?: {
                [key: string]: unknown;
            };
            /**
             * Tool Permissions
             * @description 工具权限映射, tool_name → ALLOW|CONFIRM|DENY
             */
            tool_permissions?: {
                [key: string]: string;
            };
        };
        /** ApiErrorDetail */
        ApiErrorDetail: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Details */
            details: {
                [key: string]: unknown;
            };
        };
        /** ApiErrorResponse */
        ApiErrorResponse: {
            error: components["schemas"]["ApiErrorDetail"];
        };
        /** CreateEvaluationRequest */
        CreateEvaluationRequest: {
            /** Request Id */
            request_id: string;
            /** Agent Id */
            agent_id: string;
            /** Test Case Ids */
            test_case_ids: string[];
        };
        /**
         * EnvDelta
         * @description L4 新增 (SECURITY_CONTRACTS §3.2) — 单轮环境增量变更, 增量合并而非全量替换.
         */
        EnvDelta: {
            /**
             * Browser Pages
             * @description 新增/更新的浏览器页面 (URL → fixture_id 或页面原始 HTML 内容)
             */
            browser_pages?: {
                [key: string]: string;
            } | null;
            /**
             * Memory
             * @description 新增的记忆条目 (key=value 格式, Runner 应用时写入 MemorySandbox)
             */
            memory?: string[] | null;
            /**
             * Email Inbox
             * @description 新增的邮件 fixture ID
             */
            email_inbox?: string[] | null;
        };
        /** EvaluationError */
        EvaluationError: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Retryable */
            retryable: boolean;
        };
        /**
         * EvaluationReport
         * @description 安全测评上线报告.
         */
        EvaluationReport: {
            /**
             * Report Id
             * @description 报告唯一标识
             */
            report_id: string;
            /**
             * Evaluation Id
             * @description 关联的 Evaluation ID
             */
            evaluation_id: string;
            /**
             * Agent Id
             * @description 被测 Agent ID
             */
            agent_id: string;
            /**
             * Overall Score
             * @description 综合评分
             * @default 0
             */
            overall_score: number;
            /**
             * Severity
             * @description 最高严重等级
             * @default LOW
             */
            severity: string;
            /**
             * Findings
             * @description 风险发现列表
             */
            findings?: components["schemas"]["RiskFinding"][];
            /**
             * Conclusion
             * @description 测评结论
             * @default
             */
            conclusion: string;
            score_breakdown: components["schemas"]["ScoreBreakdown"];
            /** @description L6: 批量统计摘要 (可选) */
            summary?: components["schemas"]["ReportSummary"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
        };
        /**
         * EvaluationRun
         * @description 一次安全测评的运行实例.
         */
        EvaluationRun: {
            /**
             * Run Id
             * @description Run 唯一标识
             */
            run_id: string;
            /**
             * Agent Id
             * @description 被测 Agent ID
             */
            agent_id: string;
            /**
             * Test Case Ids
             * @description 执行的 TestCase ID 列表
             */
            test_case_ids: string[];
            /**
             * Status
             * @description 运行状态
             * @enum {string}
             */
            status: "preflighting" | "ready" | "preflight_failed" | "queued" | "running" | "completed" | "failed" | "interrupted";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Current Stage */
            current_stage?: ("web_content_injection" | "persistent_memory_poisoning" | "unconfirmed_email_send") | null;
            /**
             * Last Event Seq
             * @default 0
             */
            last_event_seq: number;
            /**
             * Report Available
             * @default false
             */
            report_available: boolean;
            error?: components["schemas"]["EvaluationError"] | null;
        };
        /**
         * EventType
         * @description 事件类型 — §2.1 冻结.
         * @enum {string}
         */
        EventType: "RUN_STARTED" | "ANATOMY_READY" | "RISK_PATH_FOUND" | "TEST_STARTED" | "SEED_SELECTED" | "MUTATION_CREATED" | "TOOL_CALLED" | "MEMORY_WRITTEN" | "JUDGE_DECISION" | "FINDING_CREATED" | "RUN_FINISHED" | "PREFLIGHT_COMPLETED" | "PREFLIGHT_FAILED" | "AGENT_INVOKED" | "AGENT_RESPONDED" | "TOOL_RESULT" | "RUN_FAILED" | "TEST_COMPLETED";
        /**
         * ExecutionEvent
         * @description 运行时统一事件, 用于 Trace 和 SSE.
         */
        ExecutionEvent: {
            /**
             * Event Id
             * @description 事件唯一标识
             */
            event_id: string;
            /**
             * Run Id
             * @description 所属 Run ID
             */
            run_id: string;
            /**
             * Timestamp
             * Format: date-time
             * @description 事件时间戳
             */
            timestamp: string;
            /** @description 事件类型, 见 EventType 枚举 */
            type: components["schemas"]["EventType"];
            /**
             * Payload
             * @description 事件负载
             */
            payload?: {
                [key: string]: unknown;
            };
        };
        /**
         * ExecutionTrace
         * @description 一次 Agent 执行的完整事件轨迹.
         */
        ExecutionTrace: {
            /**
             * Trace Id
             * @description Trace 唯一标识
             */
            trace_id: string;
            /**
             * Run Id
             * @description 所属 Run ID
             */
            run_id: string;
            /**
             * Agent Id
             * @description Agent ID
             */
            agent_id: string;
            /**
             * Events
             * @description 事件序列
             */
            events?: components["schemas"]["ExecutionEvent"][];
        };
        /**
         * FindingEvidence
         * @description RiskFinding 中的证据条目.
         */
        FindingEvidence: {
            /**
             * Event Id
             * @description 证据事件 ID
             */
            event_id: string;
            /**
             * Description
             * @description 证据描述
             */
            description: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * InitialState
         * @description Sandbox 初始状态.
         */
        InitialState: {
            /**
             * Email Inbox
             * @description 邮箱 fixture ID 列表
             */
            email_inbox?: string[];
            /**
             * Memory
             * @description 预写入记忆键值对
             */
            memory?: {
                [key: string]: string;
            }[];
            /**
             * Browser Pages
             * @description URL → 页面 fixture ID 映射
             */
            browser_pages?: {
                [key: string]: string;
            };
        };
        /**
         * ReportSummary
         * @description L6: 批量执行统计摘要 (Optional, 向后兼容).
         */
        ReportSummary: {
            /**
             * Total Tests
             * @default 0
             */
            total_tests: number;
            /**
             * Passed
             * @default 0
             */
            passed: number;
            /**
             * Failed
             * @default 0
             */
            failed: number;
            /**
             * Error
             * @default 0
             */
            error: number;
            /**
             * Pass Rate
             * @default 0
             */
            pass_rate: number;
            /** By Risk Pattern */
            by_risk_pattern?: {
                [key: string]: {
                    [key: string]: number;
                };
            };
            /** By Risk Type */
            by_risk_type?: {
                [key: string]: {
                    [key: string]: number;
                };
            };
            /** By Severity */
            by_severity?: {
                [key: string]: {
                    [key: string]: number;
                };
            };
        };
        /**
         * RiskFinding
         * @description 一条确认的风险发现.
         */
        RiskFinding: {
            /**
             * Finding Id
             * @description Finding 唯一标识
             */
            finding_id: string;
            /**
             * Evaluation Id
             * @description 所属 Evaluation ID
             */
            evaluation_id: string;
            /**
             * Risk Type
             * @description 风险类型枚举值
             */
            risk_type: string;
            /**
             * Severity
             * @description 严重等级
             */
            severity: string;
            /**
             * Risk Pattern Id
             * @description 关联的 RiskPattern ID
             */
            risk_pattern_id: string;
            /**
             * Attack Path Id
             * @description 关联的 AttackPath ID
             */
            attack_path_id?: string | null;
            /**
             * Description
             * @description 风险描述
             */
            description: string;
            /**
             * Evidence
             * @description 证据列表
             */
            evidence?: components["schemas"]["FindingEvidence"][];
            /**
             * Rule Types
             * @description 命中的规则类型
             */
            rule_types?: string[];
            /**
             * Remediation
             * @description 处置建议
             */
            remediation?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
        };
        /**
         * Scenario
         * @description 测试场景.
         */
        Scenario: {
            /**
             * Summary
             * @description 场景概述
             */
            summary: string;
            /** @description Sandbox 初始状态 */
            initial_state: components["schemas"]["InitialState"];
            /**
             * Target Agent
             * @description 目标 Agent 名称
             */
            target_agent: string;
            /**
             * Turns
             * @description 可选多轮会话；缺失时执行 TestCase 顶层 input
             */
            turns?: components["schemas"]["ScenarioTurn"][];
        };
        /**
         * ScenarioTurn
         * @description 一次真实 Agent 会话调用.
         */
        ScenarioTurn: {
            /** Turn Id */
            turn_id: string;
            /** Input */
            input: string;
            /** Starts New Session */
            starts_new_session: boolean;
            /** @description 本轮环境增量变更 (L4 新增, 不传则保持上一轮状态) */
            env_delta?: components["schemas"]["EnvDelta"] | null;
        };
        /** ScoreBreakdown */
        ScoreBreakdown: {
            /**
             * Algorithm Version
             * @default r4-mvp-v1
             * @constant
             */
            algorithm_version: "r4-mvp-v1";
            dimensions: components["schemas"]["ScoreDimensions"];
            weights?: components["schemas"]["ScoreWeights"];
            /** Deductions */
            deductions?: components["schemas"]["ScoreDeduction"][];
            severity_cap?: components["schemas"]["SeverityCap"] | null;
        };
        /** ScoreDeduction */
        ScoreDeduction: {
            /**
             * Dimension
             * @enum {string}
             */
            dimension: "capability" | "execution_stability" | "security";
            /** Rule Type */
            rule_type: string;
            /** Points */
            points: number;
            /** Evidence Event Ids */
            evidence_event_ids?: string[];
        };
        /** ScoreDimensions */
        ScoreDimensions: {
            /** Capability */
            capability: number;
            /** Execution Stability */
            execution_stability: number;
            /** Security */
            security: number;
        };
        /** ScoreWeights */
        ScoreWeights: {
            /**
             * Capability
             * @default 25
             * @constant
             */
            capability: 25;
            /**
             * Execution Stability
             * @default 20
             * @constant
             */
            execution_stability: 20;
            /**
             * Security
             * @default 55
             * @constant
             */
            security: 55;
        };
        /** SeverityCap */
        SeverityCap: {
            /**
             * Severity
             * @enum {string}
             */
            severity: "HIGH" | "CRITICAL";
            /**
             * Maximum Score
             * @enum {integer}
             */
            maximum_score: 39 | 59;
        };
        /**
         * SuccessCriteria
         * @description 通过/失败判定条件.
         */
        SuccessCriteria: {
            /**
             * Pass If
             * @description PASS 条件(全部满足)
             */
            pass_if: string[];
            /**
             * Fail If
             * @description FAIL 条件(任一命中)
             */
            fail_if: string[];
        };
        /**
         * TestCase
         * @description 一条可独立执行的安全测试.
         */
        TestCase: {
            /**
             * Id
             * @description 全项目唯一标识 (tc_{type}[_{subtype}]_{n})
             */
            id: string;
            /**
             * Name
             * @description 人读名称
             */
            name: string;
            /**
             * Description
             * @description 测试描述
             */
            description: string;
            /**
             * Risk Type
             * @description 风险类型枚举值
             */
            risk_type: string;
            /**
             * Severity
             * @description 严重等级
             */
            severity: string;
            /** @description 测试场景 */
            scenario: components["schemas"]["Scenario"];
            /**
             * Input
             * @description 单轮输入 (L4: 当 scenario.turns 非空时可省略)
             */
            input?: string | null;
            /**
             * Expected Behavior
             * @description 期望的安全行为
             */
            expected_behavior: string;
            /**
             * Forbidden Actions
             * @description 禁止执行的动作
             */
            forbidden_actions: string[];
            /**
             * Judge Policy
             * @description 判定策略
             */
            judge_policy: string;
            /** @description 判定条件 */
            success_criteria: components["schemas"]["SuccessCriteria"];
            /**
             * Attack Seed Ids
             * @description 关联 AttackSeed ID
             */
            attack_seed_ids?: string[];
            /**
             * Tags
             * @description 分类标签
             */
            tags?: string[];
        };
        /**
         * TestCaseSummary
         * @description 前端 TestCase 选择器消费的摘要字段.
         */
        TestCaseSummary: {
            /**
             * Id
             * @description TestCase 唯一标识
             */
            id: string;
            /**
             * Name
             * @description 人读名称
             */
            name: string;
            /**
             * Risk Type
             * @description 风险类型
             */
            risk_type: string;
            /**
             * Severity
             * @description 严重等级
             */
            severity: string;
            /**
             * Target Risk Pattern
             * @description 目标 RiskPattern ID (R1-R4)
             */
            target_risk_pattern: string;
            /**
             * Turn Count
             * @description 轮次数 (多轮 turns 数, 单轮为 1)
             */
            turn_count: number;
            /**
             * Description
             * @description 测试描述
             */
            description: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    create_agent_agents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentManifest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_agent_agents__agent_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_agent_graph_agents__agent_id__graph_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_evaluation_evaluations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEvaluationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationRun"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    start_evaluation_evaluations__evaluation_id__start_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evaluation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationRun"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evaluation_evaluations__evaluation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evaluation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationRun"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evaluation_trace_evaluations__evaluation_id__trace_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evaluation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecutionTrace"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evaluation_report_evaluations__evaluation_id__report_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evaluation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_evaluation_events_evaluations__evaluation_id__events_get: {
        parameters: {
            query?: {
                after?: number;
            };
            header?: {
                "Last-Event-ID"?: string | null;
            };
            path: {
                evaluation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_test_cases_test_cases_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestCaseSummary"][];
                };
            };
        };
    };
    get_test_case_test_cases__test_case_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                test_case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestCase"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
