/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Agent
         * @description Register a new Agent from its manifest. Returns AgentProfile.
         */
        post: operations["create_agent_agents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/{agent_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Agent
         * @description Get AgentProfile by ID.
         */
        get: operations["get_agent_agents__agent_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/{agent_id}/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Agent Graph
         * @description Get AttackGraph for an agent.
         */
        get: operations["get_agent_graph_agents__agent_id__graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evaluations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Evaluation */
        post: operations["create_evaluation_evaluations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evaluations/comparisons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Evaluation Comparison */
        post: operations["create_evaluation_comparison_evaluations_comparisons_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evaluations/comparisons/{comparison_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Evaluation Comparison */
        get: operations["get_evaluation_comparison_evaluations_comparisons__comparison_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evaluations/comparisons/{comparison_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Evaluation Comparison Report */
        get: operations["get_evaluation_comparison_report_evaluations_comparisons__comparison_id__report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evaluations/comparisons/{comparison_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Evaluation Comparison */
        post: operations["retry_evaluation_comparison_evaluations_comparisons__comparison_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evaluations/comparisons/{comparison_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Evaluation Comparison Events */
        get: operations["stream_evaluation_comparison_events_evaluations_comparisons__comparison_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evaluations/{evaluation_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Evaluation */
        post: operations["start_evaluation_evaluations__evaluation_id__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evaluations/{evaluation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Evaluation */
        get: operations["get_evaluation_evaluations__evaluation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evaluations/{evaluation_id}/trace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Evaluation Trace */
        get: operations["get_evaluation_trace_evaluations__evaluation_id__trace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evaluations/{evaluation_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Evaluation Report */
        get: operations["get_evaluation_report_evaluations__evaluation_id__report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evaluations/{evaluation_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Evaluation Events */
        get: operations["stream_evaluation_events_evaluations__evaluation_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/test-cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Test Cases
         * @description ����ȫ�� TestCase ժҪ (��ǰ��ѡ���� + OpenAPI types ����).
         */
        get: operations["list_test_cases_test_cases_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/test-cases/{test_case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Test Case
         * @description ���ص������� TestCase (�� scenario.turns + env_delta), ��ǰ��/��������.
         *
         *     L4 ǩ�ֱ�ע: Frontend �� OpenAPI schema Ϊ׼, ���� ScenarioTurn.input /
         *     ScenarioTurn.env_delta / turn_count ���ֶΡ�
         */
        get: operations["get_test_case_test_cases__test_case_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evaluations/comparisons/{comparison_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Evaluation Comparison */
        post: operations["start_evaluation_comparison_evaluations_comparisons__comparison_id__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AgentManifest
         * @description �û����� Agent ʱ�ύ�������ļ�.
         */
        AgentManifest: {
            /**
             * Agent Id
             * @description Agent Ψһ��ʶ
             */
            agent_id: string;
            /**
             * Name
             * @description Agent ����
             */
            name: string;
            /**
             * Version
             * @description �汾��
             * @default 0.1.0
             */
            version: string;
            /**
             * Capabilities
             * @description �����嵥(������)
             */
            capabilities?: string[];
            /**
             * Data Sources
             * @description ����Դ�б�
             */
            data_sources?: string[];
            /**
             * Memory
             * @description ��������
             */
            memory?: {
                [key: string]: unknown;
            };
            /**
             * Tool Permissions
             * @description ����Ȩ��ӳ��, tool_name �� ALLOW|CONFIRM|DENY
             */
            tool_permissions?: {
                [key: string]: string;
            };
        };
        /** ApiErrorDetail */
        ApiErrorDetail: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Details */
            details: {
                [key: string]: unknown;
            };
        };
        /** ApiErrorResponse */
        ApiErrorResponse: {
            error: components["schemas"]["ApiErrorDetail"];
        };
        /** CreateEvaluationComparisonRequest */
        CreateEvaluationComparisonRequest: {
            /** Request Id */
            request_id: string;
            /** Test Case Ids */
            test_case_ids: string[];
        };
        /** CreateEvaluationRequest */
        CreateEvaluationRequest: {
            /** Request Id */
            request_id: string;
            /** Agent Id */
            agent_id: string;
            /** Test Case Ids */
            test_case_ids: string[];
        };
        /**
         * EnvDelta
         * @description L4 ���� (SECURITY_CONTRACTS ��3.2) �� ���ֻ����������, �����ϲ�����ȫ���滻.
         */
        EnvDelta: {
            /**
             * Browser Pages
             * @description ����/���µ������ҳ�� (URL �� fixture_id ��ҳ��ԭʼ HTML ����)
             */
            browser_pages?: {
                [key: string]: string;
            } | null;
            /**
             * Memory
             * @description �����ļ�����Ŀ (key=value ��ʽ, Runner Ӧ��ʱд�� MemorySandbox)
             */
            memory?: string[] | null;
            /**
             * Email Inbox
             * @description �������ʼ� fixture ID
             */
            email_inbox?: string[] | null;
        };
        /** EvaluationComparisonReport */
        EvaluationComparisonReport: {
            /** Comparison Id */
            comparison_id: string;
            /** Mode */
            mode: string;
            /** Test Case Ids */
            test_case_ids: string[];
            /** Status */
            status: string;
            /** Bare Run Id */
            bare_run_id: string;
            /** Defended Run Id */
            defended_run_id: string | null;
            /** Summary */
            summary: {
                [key: string]: unknown;
            };
            /** Results */
            results: {
                [key: string]: unknown;
            }[];
        };
        /** EvaluationComparisonSnapshot */
        EvaluationComparisonSnapshot: {
            /** Comparison Id */
            comparison_id: string;
            /**
             * Mode
             * @constant
             */
            mode: "bare_vs_defended";
            /** Test Case Ids */
            test_case_ids: string[];
            /** Bare Run Id */
            bare_run_id: string;
            /** Defended Run Id */
            defended_run_id?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "creating" | "queued" | "running_bare" | "running_defended" | "running_parallel" | "completed" | "partial" | "failed";
            /** Comparison Seed */
            comparison_seed: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Bare Agent Id
             * @default llm-agent-v0
             */
            bare_agent_id: string;
            /**
             * Defended Agent Id
             * @default defended-llm-v0
             */
            defended_agent_id: string;
            bare_run: components["schemas"]["EvaluationRun"];
            defended_run?: components["schemas"]["EvaluationRun"] | null;
        };
        /** EvaluationError */
        EvaluationError: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Retryable */
            retryable: boolean;
        };
        /**
         * EvaluationReport
         * @description ��ȫ�������߱���.
         */
        EvaluationReport: {
            /**
             * Report Id
             * @description ����Ψһ��ʶ
             */
            report_id: string;
            /**
             * Evaluation Id
             * @description ������ Evaluation ID
             */
            evaluation_id: string;
            /**
             * Agent Id
             * @description ���� Agent ID
             */
            agent_id: string;
            /**
             * Overall Score
             * @description �ۺ�����
             * @default 0
             */
            overall_score: number;
            /**
             * Severity
             * @description ������صȼ�
             * @default LOW
             */
            severity: string;
            /**
             * Findings
             * @description ���շ����б�
             */
            findings?: components["schemas"]["RiskFinding"][];
            /**
             * Conclusion
             * @description ��������
             * @default
             */
            conclusion: string;
            score_breakdown: components["schemas"]["ScoreBreakdown"];
            /** @description L6: ����ͳ��ժҪ (��ѡ) */
            summary?: components["schemas"]["ReportSummary"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
        };
        /**
         * EvaluationRun
         * @description һ�ΰ�ȫ����������ʵ��.
         */
        EvaluationRun: {
            /**
             * Run Id
             * @description Run Ψһ��ʶ
             */
            run_id: string;
            /**
             * Agent Id
             * @description ���� Agent ID
             */
            agent_id: string;
            /**
             * Test Case Ids
             * @description ִ�е� TestCase ID �б�
             */
            test_case_ids: string[];
            /**
             * Status
             * @description ����״̬
             * @enum {string}
             */
            status: "preflighting" | "ready" | "preflight_failed" | "queued" | "running" | "completed" | "failed" | "interrupted";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Current Stage */
            current_stage?: ("web_content_injection" | "persistent_memory_poisoning" | "unconfirmed_email_send") | null;
            /**
             * Last Event Seq
             * @default 0
             */
            last_event_seq: number;
            /**
             * Report Available
             * @default false
             */
            report_available: boolean;
            error?: components["schemas"]["EvaluationError"] | null;
        };
        /**
         * EventType
         * @description �¼����� �� ��2.1 ����.
         * @enum {string}
         */
        EventType: "RUN_STARTED" | "ANATOMY_READY" | "RISK_PATH_FOUND" | "TEST_STARTED" | "SEED_SELECTED" | "MUTATION_CREATED" | "TOOL_CALLED" | "MEMORY_WRITTEN" | "JUDGE_DECISION" | "FINDING_CREATED" | "RUN_FINISHED" | "PREFLIGHT_COMPLETED" | "PREFLIGHT_FAILED" | "AGENT_INVOKED" | "AGENT_RESPONDED" | "TOOL_RESULT" | "RUN_FAILED" | "TEST_COMPLETED";
        /**
         * ExecutionEvent
         * @description ����ʱͳһ�¼�, ���� Trace �� SSE.
         */
        ExecutionEvent: {
            /**
             * Event Id
             * @description �¼�Ψһ��ʶ
             */
            event_id: string;
            /**
             * Run Id
             * @description ���� Run ID
             */
            run_id: string;
            /**
             * Timestamp
             * Format: date-time
             * @description �¼�ʱ���
             */
            timestamp: string;
            /** @description �¼�����, �� EventType ö�� */
            type: components["schemas"]["EventType"];
            /**
             * Payload
             * @description �¼�����
             */
            payload?: {
                [key: string]: unknown;
            };
        };
        /**
         * ExecutionTrace
         * @description һ�� Agent ִ�е������¼��켣.
         */
        ExecutionTrace: {
            /**
             * Trace Id
             * @description Trace Ψһ��ʶ
             */
            trace_id: string;
            /**
             * Run Id
             * @description ���� Run ID
             */
            run_id: string;
            /**
             * Agent Id
             * @description Agent ID
             */
            agent_id: string;
            /**
             * Events
             * @description �¼�����
             */
            events?: components["schemas"]["ExecutionEvent"][];
        };
        /**
         * FindingEvidence
         * @description RiskFinding �е�֤����Ŀ.
         */
        FindingEvidence: {
            /**
             * Event Id
             * @description ֤���¼� ID
             */
            event_id: string;
            /**
             * Description
             * @description ֤������
             */
            description: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * InitialState
         * @description Sandbox ��ʼ״̬.
         */
        InitialState: {
            /**
             * Email Inbox
             * @description ���� fixture ID �б�
             */
            email_inbox?: string[];
            /**
             * Memory
             * @description Ԥд������ֵ��
             */
            memory?: {
                [key: string]: string;
            }[];
            /**
             * Browser Pages
             * @description URL �� ҳ�� fixture ID ӳ��
             */
            browser_pages?: {
                [key: string]: string;
            };
        };
        /**
         * ReportSummary
         * @description L6: ����ִ��ͳ��ժҪ (Optional, ������).
         */
        ReportSummary: {
            /**
             * Total Tests
             * @default 0
             */
            total_tests: number;
            /**
             * Passed
             * @default 0
             */
            passed: number;
            /**
             * Failed
             * @default 0
             */
            failed: number;
            /**
             * Error
             * @default 0
             */
            error: number;
            /**
             * Pass Rate
             * @default 0
             */
            pass_rate: number;
            /** By Risk Pattern */
            by_risk_pattern?: {
                [key: string]: {
                    [key: string]: number;
                };
            };
            /** By Risk Type */
            by_risk_type?: {
                [key: string]: {
                    [key: string]: number;
                };
            };
            /** By Severity */
            by_severity?: {
                [key: string]: {
                    [key: string]: number;
                };
            };
        };
        /** RetryEvaluationComparisonRequest */
        RetryEvaluationComparisonRequest: {
            /** Side */
            side: string;
        };
        /**
         * RiskFinding
         * @description һ��ȷ�ϵķ��շ���.
         */
        RiskFinding: {
            /**
             * Finding Id
             * @description Finding Ψһ��ʶ
             */
            finding_id: string;
            /**
             * Evaluation Id
             * @description ���� Evaluation ID
             */
            evaluation_id: string;
            /**
             * Risk Type
             * @description ��������ö��ֵ
             */
            risk_type: string;
            /**
             * Severity
             * @description ���صȼ�
             */
            severity: string;
            /**
             * Risk Pattern Id
             * @description ������ RiskPattern ID
             */
            risk_pattern_id: string;
            /**
             * Attack Path Id
             * @description ������ AttackPath ID
             */
            attack_path_id?: string | null;
            /**
             * Description
             * @description ��������
             */
            description: string;
            /**
             * Evidence
             * @description ֤���б�
             */
            evidence?: components["schemas"]["FindingEvidence"][];
            /**
             * Rule Types
             * @description ���еĹ�������
             */
            rule_types?: string[];
            /**
             * Remediation
             * @description ���ý���
             */
            remediation?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
        };
        /**
         * Scenario
         * @description ���Գ���.
         */
        Scenario: {
            /**
             * Summary
             * @description ��������
             */
            summary: string;
            /** @description Sandbox ��ʼ״̬ */
            initial_state: components["schemas"]["InitialState"];
            /**
             * Target Agent
             * @description Ŀ�� Agent ����
             */
            target_agent: string;
            /**
             * Turns
             * @description ��ѡ���ֻỰ��ȱʧʱִ�� TestCase ���� input
             */
            turns?: components["schemas"]["ScenarioTurn"][];
        };
        /**
         * ScenarioTurn
         * @description һ����ʵ Agent �Ự����.
         */
        ScenarioTurn: {
            /** Turn Id */
            turn_id: string;
            /** Input */
            input: string;
            /** Starts New Session */
            starts_new_session: boolean;
            /** @description ���ֻ���������� (L4 ����, �����򱣳���һ��״̬) */
            env_delta?: components["schemas"]["EnvDelta"] | null;
        };
        /** ScoreBreakdown */
        ScoreBreakdown: {
            /**
             * Algorithm Version
             * @default r4-mvp-v1
             * @constant
             */
            algorithm_version: "r4-mvp-v1";
            dimensions: components["schemas"]["ScoreDimensions"];
            weights?: components["schemas"]["ScoreWeights"];
            /** Deductions */
            deductions?: components["schemas"]["ScoreDeduction"][];
            severity_cap?: components["schemas"]["SeverityCap"] | null;
        };
        /** ScoreDeduction */
        ScoreDeduction: {
            /**
             * Dimension
             * @enum {string}
             */
            dimension: "capability" | "execution_stability" | "security";
            /** Rule Type */
            rule_type: string;
            /** Points */
            points: number;
            /** Evidence Event Ids */
            evidence_event_ids?: string[];
        };
        /** ScoreDimensions */
        ScoreDimensions: {
            /** Capability */
            capability: number;
            /** Execution Stability */
            execution_stability: number;
            /** Security */
            security: number;
        };
        /** ScoreWeights */
        ScoreWeights: {
            /**
             * Capability
             * @default 25
             * @constant
             */
            capability: 25;
            /**
             * Execution Stability
             * @default 20
             * @constant
             */
            execution_stability: 20;
            /**
             * Security
             * @default 55
             * @constant
             */
            security: 55;
        };
        /** SeverityCap */
        SeverityCap: {
            /**
             * Severity
             * @enum {string}
             */
            severity: "HIGH" | "CRITICAL";
            /**
             * Maximum Score
             * @enum {integer}
             */
            maximum_score: 39 | 59;
        };
        /**
         * SuccessCriteria
         * @description ͨ��/ʧ���ж�����.
         */
        SuccessCriteria: {
            /**
             * Pass If
             * @description PASS ����(ȫ������)
             */
            pass_if: string[];
            /**
             * Fail If
             * @description FAIL ����(��һ����)
             */
            fail_if: string[];
        };
        /**
         * TestCase
         * @description һ���ɶ���ִ�еİ�ȫ����.
         */
        TestCase: {
            /**
             * Id
             * @description ȫ��ĿΨһ��ʶ (tc_{type}[_{subtype}]_{n})
             */
            id: string;
            /**
             * Name
             * @description �˶�����
             */
            name: string;
            /**
             * Description
             * @description ��������
             */
            description: string;
            /**
             * Risk Type
             * @description ��������ö��ֵ
             */
            risk_type: string;
            /**
             * Severity
             * @description ���صȼ�
             */
            severity: string;
            /** @description ���Գ��� */
            scenario: components["schemas"]["Scenario"];
            /**
             * Input
             * @description �������� (L4: �� scenario.turns �ǿ�ʱ��ʡ��)
             */
            input?: string | null;
            /**
             * Expected Behavior
             * @description �����İ�ȫ��Ϊ
             */
            expected_behavior: string;
            /**
             * Forbidden Actions
             * @description ��ִֹ�еĶ���
             */
            forbidden_actions: string[];
            /**
             * Judge Policy
             * @description �ж�����
             */
            judge_policy: string;
            /** @description �ж����� */
            success_criteria: components["schemas"]["SuccessCriteria"];
            /**
             * Attack Seed Ids
             * @description ���� AttackSeed ID
             */
            attack_seed_ids?: string[];
            /**
             * Tags
             * @description �����ǩ
             */
            tags?: string[];
        };
        /**
         * TestCaseSummary
         * @description ǰ�� TestCase ѡ�������ѵ�ժҪ�ֶ�.
         */
        TestCaseSummary: {
            /**
             * Id
             * @description TestCase Ψһ��ʶ
             */
            id: string;
            /**
             * Name
             * @description �˶�����
             */
            name: string;
            /**
             * Risk Type
             * @description ��������
             */
            risk_type: string;
            /**
             * Severity
             * @description ���صȼ�
             */
            severity: string;
            /**
             * Target Risk Pattern
             * @description Ŀ�� RiskPattern ID (R1-R4)
             */
            target_risk_pattern: string;
            /**
             * Turn Count
             * @description �ִ��� (���� turns ��, ����Ϊ 1)
             */
            turn_count: number;
            /**
             * Description
             * @description ��������
             */
            description: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    create_agent_agents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentManifest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_agent_agents__agent_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_agent_graph_agents__agent_id__graph_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_evaluation_evaluations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEvaluationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationRun"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    create_evaluation_comparison_evaluations_comparisons_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEvaluationComparisonRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationComparisonSnapshot"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    get_evaluation_comparison_evaluations_comparisons__comparison_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                comparison_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationComparisonSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evaluation_comparison_report_evaluations_comparisons__comparison_id__report_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                comparison_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationComparisonReport"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_evaluation_comparison_evaluations_comparisons__comparison_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                comparison_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetryEvaluationComparisonRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationComparisonSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_evaluation_comparison_events_evaluations_comparisons__comparison_id__events_get: {
        parameters: {
            query?: {
                after?: number;
            };
            header?: {
                "Last-Event-ID"?: string | null;
            };
            path: {
                comparison_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_evaluation_evaluations__evaluation_id__start_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evaluation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationRun"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evaluation_evaluations__evaluation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evaluation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationRun"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evaluation_trace_evaluations__evaluation_id__trace_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evaluation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecutionTrace"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evaluation_report_evaluations__evaluation_id__report_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evaluation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_evaluation_events_evaluations__evaluation_id__events_get: {
        parameters: {
            query?: {
                after?: number;
            };
            header?: {
                "Last-Event-ID"?: string | null;
            };
            path: {
                evaluation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_test_cases_test_cases_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestCaseSummary"][];
                };
            };
        };
    };
    get_test_case_test_cases__test_case_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                test_case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestCase"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_evaluation_comparison_evaluations_comparisons__comparison_id__start_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                comparison_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationComparisonSnapshot"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
